[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_student_intro_program = "7aHbT8gpfAjCvNZtkJk3dsPQJSWBGAGoAv9XK8TEodDQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
